### ISSUE TITLE
[Yum Yum] Improve accuracy

### ISSUE THREAD

**Issue by choikk** [DreamCatchers16105/MDState2017#1]
Yum Yum is too sensitive for the starting point and angle.  It fails or mis-aligns on or after the bat food depending on the starting position and angle.  This must be improved to be completely successful on all 4 foodie missions.

**Comment by silverdragon360** [comment]
We have added an ultrasonic (distance) sensor to solve this problem. It is much more accurate now, however, it still could miss if we line up too far to the right.
